
import { Question } from './types';

export const QUESTIONS: Question[] = [
  // EXERCISE 1: VERB FORMS (Questions 1-30)
  { id: 1, type: 'fill', content: 'The instructor warned the sportsman (not repeat) ______ that mistake.', correctAnswer: 'not to repeat' },
  { id: 2, type: 'fill', content: '"What did you ask him that upset him so much?" - "I asked him if he (plan) ______ to get married again."', correctAnswer: 'planned' },
  { id: 3, type: 'fill', content: 'Having finished her presentation, the speaker asked if anyone (have) ______ any questions.', correctAnswer: 'had' },
  { id: 4, type: 'fill', content: 'The MP asked if the Prime Minister (be) ______ aware of the growing social problems.', correctAnswer: 'was' },
  { id: 5, type: 'fill', content: 'He said that he (go) ______ abroad for a year if he (be) ______ me.', correctAnswer: 'would go, were' },
  { id: 6, type: 'fill', content: 'John told me that when he (see) ______ my sister, she (talk) ______ with a handsome man.', correctAnswer: 'saw, was talking' },
  { id: 7, type: 'fill', content: 'Peter said that if he (be) ______ rich he (travel) ______ a lot.', correctAnswer: 'were, would travel' },
  { id: 8, type: 'fill', content: 'I asked him whose car he (borrow) ______ the previous night.', correctAnswer: 'had borrowed' },
  { id: 9, type: 'fill', content: 'They asked me if my brother (work) ______ in London then.', correctAnswer: 'was working' },
  { id: 10, type: 'fill', content: 'He asked the children (not make) ______ too much noise.', correctAnswer: 'not to make' },
  { id: 11, type: 'fill', content: 'The woman asked whether the children (can get) ______ lunch at school or not.', correctAnswer: 'could get' },
  { id: 12, type: 'fill', content: 'James said that he (must) ______ take the early bus that morning.', correctAnswer: 'had to' },
  { id: 13, type: 'fill', content: 'We asked the guide if it (be) ______ safe to stay in the mountains if the weather (not change) ______.', correctAnswer: 'was, did not change' },
  { id: 14, type: 'fill', content: 'Peter told me that Daisy (look) ______ frightened as if something terrible (happen) ______.', correctAnswer: 'looked, had happened' },
  { id: 15, type: 'fill', content: 'My brother said that if oil (pour) ______ into water, it (float) ______ on the surface.', correctAnswer: 'is poured, floats' },
  { id: 16, type: 'fill', content: 'Laura said that when she (walk) ______ to school, she saw an accident.', correctAnswer: 'was walking' },
  { id: 17, type: 'fill', content: 'Julia said that she (be) ______ there at noon.', correctAnswer: 'would be' },
  { id: 18, type: 'fill', content: 'My parents told that they (love) ______ each other since they (be) ______ students.', correctAnswer: 'had loved, were' },
  { id: 19, type: 'fill', content: 'He asked me what I (do) ______ after I had graduated from university.', correctAnswer: 'would do' },
  { id: 20, type: 'fill', content: 'He (tell) ______ me that he is leaving that afternoon.', correctAnswer: 'told' },
  { id: 21, type: 'fill', content: 'They asked me how many children there (be) ______ in the school.', correctAnswer: 'were' },
  { id: 22, type: 'fill', content: 'The scientist said the earth (go) ______ around the sun.', correctAnswer: 'goes' },
  { id: 23, type: 'fill', content: 'The porter said that he would wake me up when the train (arrive) ______ in Leeds.', correctAnswer: 'arrived' },
  { id: 24, type: 'fill', content: 'He asked his girlfriend where she (be) ______ the night before.', correctAnswer: 'had been' },
  { id: 25, type: 'fill', content: 'She said that she (bear) ______ in 1987 but I don\'t believe.', correctAnswer: 'was born' },
  { id: 26, type: 'fill', content: 'He asked me what time I (go) ______ to bed last night.', correctAnswer: 'had gone' },
  { id: 27, type: 'fill', content: 'The doctor advised him (stop) ______ smoking.', correctAnswer: 'to stop' },
  { id: 28, type: 'fill', content: 'The teacher said that we (have) ______ a test the following week.', correctAnswer: 'would have' },
  { id: 29, type: 'fill', content: 'They told us that they (finish) ______ their work by then.', correctAnswer: 'had finished' },
  { id: 30, type: 'fill', content: 'I wondered why she (not come) ______ to the party yesterday.', correctAnswer: 'had not come' },

  // EXERCISE 2.1: TRANSFORMATION (Questions 31-80)
  { id: 31, type: 'transform', content: 'They said: "We are learning English now"', correctAnswer: 'They said they were learning English then' },
  { id: 32, type: 'transform', content: '"My friend is coming next week", Tom said.', correctAnswer: 'Tom said his friend was coming the following week' },
  { id: 33, type: 'transform', content: '"I\'ll help my mum with housework this weekend", she said.', correctAnswer: 'She said she would help her mum with housework that weekend' },
  { id: 34, type: 'transform', content: '"You will have to finish all these exercises before next week", the teacher said to his students.', correctAnswer: 'The teacher said to his students they would have to finish all those exercises before the following week' },
  { id: 35, type: 'transform', content: '"I came back here early yesterday", she said.', correctAnswer: 'She said she had come back there early the day before' },
  { id: 36, type: 'transform', content: 'Johnny said to his mother: "I don\'t know how to do this exercise."', correctAnswer: 'Johnny said to his mother he didn\'t know how to do that exercise' },
  { id: 37, type: 'transform', content: '"We are waiting for the school bus", said the children.', correctAnswer: 'The children said they were waiting for the school bus' },
  { id: 38, type: 'transform', content: 'Mary said: "I cannot go to the movies with you, John".', correctAnswer: 'Mary said to John she could not go to the movies with him' },
  { id: 39, type: 'transform', content: 'The man declared: "I shall be doing exactly the same work next Monday as I am doing today".', correctAnswer: 'The man declared he would be doing exactly the same work the following Monday as he was doing that day' },
  { id: 40, type: 'transform', content: 'The woman said: "I was born in 1954 and I have been living in this small town since I was small".', correctAnswer: 'The woman said she was born in 1954 and had been living in that small town since she was small' },
  { id: 41, type: 'transform', content: '"My teacher wants to have a talk with you tomorrow morning", Tom said.', correctAnswer: 'Tom said his teacher wanted to have a talk with me the next morning' },
  { id: 42, type: 'transform', content: 'Our teacher said: "The Second World War broke out in 1939".', correctAnswer: 'Our teacher said the Second World War broke out in 1939' },
  { id: 43, type: 'transform', content: 'Linh said: "If my father repairs the bike now, I will ride the bike to school this afternoon."', correctAnswer: 'Linh said if her father repaired the bike then, she would ride the bike to school that afternoon' },
  { id: 44, type: 'transform', content: '"I would have passed the exam if I had tried my best", Binh said.', correctAnswer: 'Binh said he would have passed the exam if he had tried his best' },
  { id: 45, type: 'transform', content: 'The young man said to her: "If you didn\'t agree with me now, I wouldn\'t meet you anymore."', correctAnswer: 'The young man said to her if she didn\'t agree with him then, he wouldn\'t meet her anymore' },
  { id: 46, type: 'transform', content: '"If you aren\'t doing homework, what will you do next?", I said to the boy.', correctAnswer: 'I asked the boy what he would do next if he wasn\'t doing homework' },
  { id: 47, type: 'transform', content: 'Quynh said to An: "If your father weren\'t a billionaire, you could save your money."', correctAnswer: 'Quynh said to An if his father weren\'t a billionaire, he could save his money' },
  { id: 48, type: 'transform', content: 'We said to Xuan: "We won\'t go camping if your family doesn\'t join with us."', correctAnswer: 'We said to Xuan we wouldn\'t go camping if her family didn\'t join with us' },
  { id: 49, type: 'transform', content: '"If my parents hadn\'t given birth to me fifteen years ago, I wouldn\'t have seen the Earth", Hoang said.', correctAnswer: 'Hoang said if his parents hadn\'t given birth to him fifteen years before, he wouldn\'t have seen the Earth' },
  { id: 50, type: 'transform', content: '"If a stranger appeared, what would you do?", he said to his brother.', correctAnswer: 'He asked his brother what he would do if a stranger appeared' },
  { id: 51, type: 'transform', content: '"Leave your address with the secretary", the assistant said to me.', correctAnswer: 'The assistant asked me to leave my address with the secretary' },
  { id: 52, type: 'transform', content: '"Phone to me for an answer tomorrow", the manager said to the client.', correctAnswer: 'The manager told the client to phone to him for an answer the next day' },
  { id: 53, type: 'transform', content: '"Don\'t leave these books on the table", the librarian said to the student.', correctAnswer: 'The librarian reminded the student not to leave those books on the table' },
  { id: 54, type: 'transform', content: '"Be a good girl and sit quietly for five minutes", the nurse said to the child.', correctAnswer: 'The nurse told the child to be a good girl and sit quietly for five minutes' },
  { id: 55, type: 'transform', content: '"Leave your things here", my companion said to me.', correctAnswer: 'My companion advised me to leave my things there' },
  { id: 56, type: 'transform', content: '"Don\'t forget to send your parents my regards", she said to me.', correctAnswer: 'She reminded me not to forget to send her regards to my parents' },
  { id: 57, type: 'transform', content: '"You should join the football team, Eric", said the teacher.', correctAnswer: 'The teacher encouraged Eric to join the football team' },
  { id: 58, type: 'transform', content: '"Remember to lock the door before you go to school", my sister said.', correctAnswer: 'My sister reminded me to remember to lock the door before I went to school' },
  { id: 59, type: 'transform', content: '"Be careful of strangers and don\'t go out at night", he said to us.', correctAnswer: 'He warned us to be careful of strangers and not to go out at night' },
  { id: 60, type: 'transform', content: '"Come and see me whenever you want", she said to him.', correctAnswer: 'She invited him to come and see her whenever he wanted' },
  { id: 61, type: 'transform', content: '"Leave here immediately!", I said to him.', correctAnswer: 'I ordered him to leave there immediately' },
  { id: 62, type: 'transform', content: '"We will shut the door if you go on getting out", said the parents to children.', correctAnswer: 'The parents threatened the children they would shut the door if they went on getting out' },
  { id: 63, type: 'transform', content: '"Please, please let me come in", he said.', correctAnswer: 'He begged to be let to come in' },
  { id: 64, type: 'transform', content: '"Have you travelled abroad much?", he asked me.', correctAnswer: 'He asked me if I had travelled abroad much' },
  { id: 65, type: 'transform', content: '"Who has written this note?", the boss asked the secretary.', correctAnswer: 'The boss asked the secretary who had written that note' },
  { id: 66, type: 'transform', content: '"Why didn\'t I remember meeting her 2 days ago?", he wondered.', correctAnswer: 'He wondered why he hadn\'t remembered meeting her 2 days before' },
  { id: 67, type: 'transform', content: '"Did you really see this happen with your own eyes?", the policeman asked the boy.', correctAnswer: 'The policeman asked the boy if he had really seen that happen with his own eyes' },
  { id: 68, type: 'transform', content: '"Did you watch the detective film on TV yesterday?", he asked her.', correctAnswer: 'He asked her if she had watched the detective film on TV the day before' },
  { id: 69, type: 'transform', content: 'Tom said to the girl: "When did you have this picture taken?"', correctAnswer: 'Tom asked the girl when she had had that picture taken' },
  { id: 70, type: 'transform', content: '"Shall we go somewhere for a cup of coffee after class?", Tom said.', correctAnswer: 'Tom suggested going somewhere for a cup of coffee after class' },
  { id: 71, type: 'transform', content: '"Would you like another cup of tea?", the landlady said to the guest.', correctAnswer: 'The landlady invited the guest to have another cup of tea' },
  { id: 72, type: 'transform', content: 'My sister said to me: "What about going to see Aunt Mary on Sunday?"', correctAnswer: 'My sister suggested going to see Aunt Mary on Sunday' },
  { id: 73, type: 'transform', content: 'She asked me: "Have you ever seen a flying saucer?"', correctAnswer: 'She asked me if I had ever seen a flying saucer' },
  { id: 74, type: 'transform', content: 'James said: "Do you want me to type this letter for you?"', correctAnswer: 'James asked me if I wanted him to type that letter for me' },
  { id: 75, type: 'transform', content: 'He asked me: "Why didn\'t you come to class yesterday?"', correctAnswer: 'He asked me why I hadn\'t come to class the day before' },
  { id: 76, type: 'transform', content: 'My friend said: "Are you going to leave tomorrow?"', correctAnswer: 'My friend asked if I was going to leave the next day' },
  { id: 77, type: 'transform', content: 'I asked Bill: "What time did you go to bed last night?"', correctAnswer: 'I asked Bill what time he had gone to bed the night before' },
  { id: 78, type: 'transform', content: '"Why don\'t we organize an English competition for our students?", said Ms Lien.', correctAnswer: 'Ms Lien suggested organizing an English competition for their students' },
  { id: 79, type: 'transform', content: '"I\'m sorry I\'m late", said Mr Thanh.', correctAnswer: 'Mr Thanh apologised for being late' },
  { id: 80, type: 'transform', content: '"Me? No, I didn\'t take Sue\'s calculator", said Bob.', correctAnswer: 'Bob denied taking Sue\'s calculator' },

  // EXERCISE 3: MULTIPLE CHOICE (Questions 81-150)
  { id: 81, type: 'multiple-choice', content: 'The shop assistant finally agreed ______ a full refund.', options: ['giving me', 'to give me', 'give to me', 'to me to give'], correctAnswer: 'to give me' },
  { id: 82, type: 'multiple-choice', content: 'Bill asked me why ______ to go shopping with me.', options: ['I hadn\'t invited him', 'hadn\'t I invited him', 'I hadn\'t him invited', 'hadn\'t him I invited'], correctAnswer: 'I hadn\'t invited him' },
  { id: 83, type: 'multiple-choice', content: '"Don\'t come to the interview late", my mom said.', options: ['My mom told me do not come to the interview late', 'My mom told me did not come to the interview late', 'My mom told me not to come to the interview late', 'My mom told me not coming to the interview late'], correctAnswer: 'My mom told me not to come to the interview late' },
  { id: 84, type: 'multiple-choice', content: '"I will help you with your CV, Mary", Peter said.', options: ['Peter advised Mary to write the CV', 'Peter promised to help Mary with her CV', 'Peter advised Mary not to write her CV', 'Peter wanted Mary to help with the CV'], correctAnswer: 'Peter promised to help Mary with her CV' },
  { id: 85, type: 'multiple-choice', content: '"______", the doctor advised his patient.', options: ['You had better stop drinking', 'You had better to drink', 'I would like you to drink', 'Please drink some more'], correctAnswer: 'You had better stop drinking' },
  { id: 86, type: 'multiple-choice', content: 'The woman said she ______ in this company for over 20 years.', options: ['has been working', 'was working', 'had been working', 'works'], correctAnswer: 'had been working' },
  { id: 87, type: 'multiple-choice', content: 'US scientists claim that they ______ a new vaccine against malaria.', options: ['were developed', 'have developed', 'had developed', 'was developing'], correctAnswer: 'have developed' },
  { id: 88, type: 'multiple-choice', content: 'If you saw a lawyer, he\'d advise you ______ legal action.', options: ['take', 'taking', 'to take', 'for taking'], correctAnswer: 'to take' },
  { id: 89, type: 'multiple-choice', content: 'The lecturer recommended ______ a number of books before the exam.', options: ['reading', 'to read', 'we reading', 'to have read'], correctAnswer: 'reading' },
  { id: 90, type: 'multiple-choice', content: 'The boss ______ because he was always behind the deadlines.', options: ['threatened to dismiss him', 'suggested him to dismiss', 'threatened him to dismiss', 'promised him to dismiss'], correctAnswer: 'threatened to dismiss him' },
  { id: 91, type: 'multiple-choice', content: '"Go ahead. Jump again", the instructor ______.', options: ['urged', 'promised', 'demanded', 'required'], correctAnswer: 'urged' },
  { id: 92, type: 'multiple-choice', content: '"______", Jim offered.', options: ['Can I get you a drink?', 'May I drink?', 'Do you want to drink?', 'Could I drink?'], correctAnswer: 'Can I get you a drink?' },
  { id: 93, type: 'multiple-choice', content: '"______", the workers refused.', options: ['We would like to work overtime', 'We had better work overtime', 'We\'re afraid that we really don\'t want to work overtime', 'We\'re willing to work overtime'], correctAnswer: 'We\'re afraid that we really don\'t want to work overtime' },
  { id: 94, type: 'multiple-choice', content: '"______", Paul reminded me.', options: ['Don\'t forget to tailor your CV to match the job descriptions', 'I would tailor your CV if you do not mind', 'I remember to tailor the CV', 'I remember tailoring your CV'], correctAnswer: 'Don\'t forget to tailor your CV to match the job descriptions' },
  { id: 95, type: 'multiple-choice', content: 'Ellie asked Stan ______ to look at the new catalogue.', options: ['did he want', 'do you want', 'whether he wants', 'if he wanted'], correctAnswer: 'if he wanted' },
  { id: 96, type: 'multiple-choice', content: 'Stephen ______ me he\'d bought that suit in a sale.', options: ['said', 'spoke', 'told', 'claimed'], correctAnswer: 'told' },
  { id: 97, type: 'multiple-choice', content: '"He said he ______ pay for the things in his bag, but I didn\'t believe him!"', options: ['is going to', 'has been going to', 'goes to', 'was going to'], correctAnswer: 'was going to' },
  { id: 98, type: 'multiple-choice', content: 'When I last saw Carrie, she told me she ______ of applying for another job, but now she\'s changed her mind.', options: ['thought', 'is thinking', 'was thinking', 'has been thinking'], correctAnswer: 'was thinking' },
  { id: 99, type: 'multiple-choice', content: '"They apologized ______ me."', options: ['to doubt', 'they had doubted', 'for doubting', 'the doubt of'], correctAnswer: 'for doubting' },
  { id: 100, type: 'multiple-choice', content: '"She asked me ______ I had ever been abroad."', options: ['that', 'whether', 'for', 'about'], correctAnswer: 'whether' },
  { id: 101, type: 'multiple-choice', content: 'Mrs Richards apologized to me ______ me a gossip in front of everybody.', options: ['to have called', 'from calling', 'that she called', 'for having called'], correctAnswer: 'for having called' },
  { id: 102, type: 'multiple-choice', content: 'She may claim ______ a PhD but nobody\'s ever actually seen the certificate.', options: ['having', 'to have', 'for having', 'if she has'], correctAnswer: 'to have' },
  { id: 103, type: 'multiple-choice', content: 'Tammy responded ______ that at least she\'d never lied to her parents.', options: ['to say', 'that she said', 'by saying', 'with having said'], correctAnswer: 'by saying' },
  { id: 104, type: 'multiple-choice', content: 'The woman asked ______ get lunch at school.', options: ['can the children', 'if the children can', 'whether the children could', 'could the children'], correctAnswer: 'whether the children could' },
  { id: 105, type: 'multiple-choice', content: 'They said they had got back ______.', options: ['the following day', 'the day after tomorrow', 'the next day', 'the previous day'], correctAnswer: 'the previous day' },
  { id: 106, type: 'multiple-choice', content: 'The accused denied ______ in the vicinity of the murder scene.', options: ['to have ever been', 'have ever been', 'having been ever', 'ever having been'], correctAnswer: 'ever having been' },
  { id: 107, type: 'multiple-choice', content: 'We complained ______ the manager ______ the poor service we received.', options: ['on - about', 'at - for', 'with - of', 'to - about'], correctAnswer: 'to - about' },
  { id: 108, type: 'multiple-choice', content: 'Police are advising ______ away from the building.', options: ['people to stay', 'people staying', 'people stay', 'people will stay'], correctAnswer: 'people to stay' },
  { id: 109, type: 'multiple-choice', content: 'The old man warned the young boys ______ in the deep river.', options: ['to swim', 'not to swim', 'don\'t swim', 'against not swimming'], correctAnswer: 'not to swim' },
  { id: 110, type: 'multiple-choice', content: 'Mrs. Vine said we ______ give her our essays.', options: ['were having to', 'will have to', 'had to', 'would have to'], correctAnswer: 'had to' },
  { id: 111, type: 'multiple-choice', content: 'I wondered ______ the right thing.', options: ['whether I was doing', 'if I am doing', 'was I doing', 'am I doing'], correctAnswer: 'whether I was doing' },
  { id: 112, type: 'multiple-choice', content: 'He ______ that he was leaving that afternoon.', options: ['told me', 'told to me', 'said me', 'says to me'], correctAnswer: 'told me' },
  { id: 113, type: 'multiple-choice', content: 'Bill asked Tom ______ in London.', options: ['does the train arrive', 'did the train arrive', 'whether the train arrives', 'if the train had arrived'], correctAnswer: 'whether the train arrives' },
  { id: 114, type: 'multiple-choice', content: 'I asked them when ______ changed.', options: ['was the timetable', 'the timetable is', 'the timetable has been', 'the timetable had been'], correctAnswer: 'the timetable had been' },
  { id: 115, type: 'multiple-choice', content: 'She warned me ______ late-night horror films.', options: ['don\'t watch', 'shouldn\'t watch', 'not to watch', 'not watching'], correctAnswer: 'not to watch' },
  { id: 116, type: 'multiple-choice', content: 'She explained she\'d been on holiday the ______ week.', options: ['ago', 'following', 'next', 'previous'], correctAnswer: 'previous' },
  { id: 117, type: 'multiple-choice', content: 'Tom has ______ this story wasn\'t completely true.', options: ['admitting that', 'was admitted that', 'admitted that', 'admit that'], correctAnswer: 'admitted that' },
  { id: 118, type: 'multiple-choice', content: 'Tom said that he ______ leave at eight.', options: ['must', 'had', 'had to', 'has to'], correctAnswer: 'had to' },
  { id: 119, type: 'multiple-choice', content: 'Mary said that she ______ to the library.', options: ['should go', 'should have gone', 'ought to go', 'better go'], correctAnswer: 'should go' },
  { id: 120, type: 'multiple-choice', content: 'I rang my friend and she said it ______ raining there.', options: ['is', 'were', 'has been', 'was'], correctAnswer: 'was' },
  { id: 121, type: 'multiple-choice', content: 'I wanted to know ______ return home.', options: ['when would she', 'when will she', 'when she will', 'when she would'], correctAnswer: 'when she would' },
  { id: 122, type: 'multiple-choice', content: 'Tom said that New York ______ more lively than London.', options: ['is', 'be', 'was', 'were'], correctAnswer: 'was' },
  { id: 123, type: 'multiple-choice', content: 'He asked why ______ the final exam.', options: ['she took', 'did she take', 'she hadn\'t taken', 'she had taken'], correctAnswer: 'she hadn\'t taken' },
  { id: 124, type: 'multiple-choice', content: 'I asked my sister to tell me what she ______ at the museum.', options: ['had seen', 'has seen', 'had been seeing', 'was seeing'], correctAnswer: 'had seen' },
  { id: 125, type: 'multiple-choice', content: 'I said that I had met her ______.', options: ['yesterday', 'the previous day', 'the day', 'before day'], correctAnswer: 'the previous day' },
  { id: 126, type: 'multiple-choice', content: 'The man asked the boys ______.', options: ['why did they fight', 'why they were fighting', 'why they fight', 'why were they fighting'], correctAnswer: 'why they were fighting' },
  { id: 127, type: 'multiple-choice', content: 'He asked me what ______.', options: ['time was it', 'time is it', 'time it was', 'None is correct'], correctAnswer: 'time it was' },
  { id: 128, type: 'multiple-choice', content: 'He told me that ______.', options: ['his father has sold the house', 'his father had sold the house the last day', 'his father will sell the house', 'his father doesn\'t sell the house'], correctAnswer: 'his father had sold the house the last day' },
  { id: 129, type: 'multiple-choice', content: 'The woman wonders ______ doing well at school.', options: ['whether her children are', 'if her children were', 'whether her children were', 'her children are if'], correctAnswer: 'whether her children were' },
  { id: 130, type: 'multiple-choice', content: 'Peter said he was leaving for Paris ______.', options: ['next week', 'the week previous', 'following week', 'the following week'], correctAnswer: 'the following week' },
  { id: 131, type: 'multiple-choice', content: 'Linda said: "Good morning, Sam! How are you?"', options: ['Linda said good morning and asked Sam how she is', 'Linda greeted Sam and asked how is she', 'Linda said good morning Sam and asked how was she', 'Linda greeted Sam and asked how he was'], correctAnswer: 'Linda greeted Sam and asked how he was' },
  { id: 132, type: 'multiple-choice', content: 'The policeman warned the man ______ his car there.', options: ['not to park', 'don\'t park', 'parking', 'not park'], correctAnswer: 'not to park' },
  { id: 133, type: 'multiple-choice', content: 'She asked me ______ my name was.', options: ['what', 'if', 'whether', 'where'], correctAnswer: 'what' },
  { id: 134, type: 'multiple-choice', content: 'They wanted to know ______.', options: ['where were we going', 'where we were going', 'where are we going', 'where we are going'], correctAnswer: 'where we were going' },
  { id: 135, type: 'multiple-choice', content: 'He asked her ______ she liked coffee.', options: ['if', 'that', 'what', 'which'], correctAnswer: 'if' },
  { id: 136, type: 'multiple-choice', content: 'The boy said he ______ all his homework.', options: ['has done', 'did', 'had done', 'does'], correctAnswer: 'had done' },
  { id: 137, type: 'multiple-choice', content: 'She said she ______ see me the next day.', options: ['will', 'would', 'shall', 'can'], correctAnswer: 'would' },
  { id: 138, type: 'multiple-choice', content: 'The teacher said the sun ______ in the East.', options: ['rose', 'rises', 'had risen', 'rising'], correctAnswer: 'rises' },
  { id: 139, type: 'multiple-choice', content: 'My mother asked me ______ I was tired.', options: ['that', 'what', 'if', 'which'], correctAnswer: 'if' },
  { id: 140, type: 'multiple-choice', content: 'He told me ______ not to shout.', options: ['to me', 'me', 'that me', 'for me'], correctAnswer: 'me' },
  { id: 141, type: 'multiple-choice', content: 'I asked her ______ she lived.', options: ['where', 'if', 'whether', 'that'], correctAnswer: 'where' },
  { id: 142, type: 'multiple-choice', content: 'They said they ______ to the cinema the night before.', options: ['went', 'had gone', 'go', 'are going'], correctAnswer: 'had gone' },
  { id: 143, type: 'multiple-choice', content: 'She asked me ______ I could help her.', options: ['if', 'what', 'how', 'where'], correctAnswer: 'if' },
  { id: 144, type: 'multiple-choice', content: 'He said he ______ busy then.', options: ['is', 'was', 'were', 'will be'], correctAnswer: 'was' },
  { id: 145, type: 'multiple-choice', content: 'The doctor advised me ______ more water.', options: ['drinking', 'to drink', 'drink', 'drank'], correctAnswer: 'to drink' },
  { id: 146, type: 'multiple-choice', content: 'She asked me ______ my brother worked.', options: ['where', 'if', 'whether', 'that'], correctAnswer: 'where' },
  { id: 147, type: 'multiple-choice', content: 'They told us they ______ for us for two hours.', options: ['waited', 'had been waiting', 'wait', 'are waiting'], correctAnswer: 'had been waiting' },
  { id: 148, type: 'multiple-choice', content: 'He said he ______ to London many times.', options: ['is', 'was', 'had been', 'will be'], correctAnswer: 'had been' },
  { id: 149, type: 'multiple-choice', content: 'She asked me ______ I was doing then.', options: ['what', 'if', 'how', 'where'], correctAnswer: 'what' },
  { id: 150, type: 'multiple-choice', content: 'The scientist said that water ______ at 100 degrees Celsius.', options: ['boils', 'boiled', 'had boiled', 'boiling'], correctAnswer: 'boils' }
];
